#!/bin/bash
# Script to help transfer OAuth files for authentication

echo "📦 OAuth File Transfer Helper"
echo "============================"
echo ""
echo "Files needed for OAuth authentication:"
echo "1. client_secrets.json"
echo "2. multi_channel_oauth_flow.py"
echo ""
echo "Current location of files:"
echo "- /home/golde/tenxsom-ai-vertex/youtube-upload-pipeline/auth/client_secrets.json"
echo "- /home/golde/tenxsom-ai-vertex/multi_channel_oauth_flow.py"
echo ""
echo "📋 OPTION 1: Copy to your local machine (from this server)"
echo "========================================================="
echo "Run these commands from your LOCAL machine:"
echo ""
echo "# Create directory and copy files"
echo "mkdir -p ~/tenxsom_oauth"
echo "cd ~/tenxsom_oauth"
echo ""
echo "# Copy client secrets"
echo "scp golde@YOUR_SERVER:/home/golde/tenxsom-ai-vertex/youtube-upload-pipeline/auth/client_secrets.json ."
echo ""
echo "# Copy OAuth flow script"
echo "scp golde@YOUR_SERVER:/home/golde/tenxsom-ai-vertex/multi_channel_oauth_flow.py ."
echo ""
echo "# Install dependencies"
echo "pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client"
echo ""
echo "# Run OAuth"
echo "python3 multi_channel_oauth_flow.py"
echo ""
echo "📋 OPTION 2: Use Google Cloud Shell"
echo "==================================="
echo "1. Go to: https://console.cloud.google.com"
echo "2. Click 'Activate Cloud Shell' button (top right)"
echo "3. In Cloud Shell, run:"
echo ""
echo "# Create directory"
echo "mkdir -p ~/tenxsom_oauth && cd ~/tenxsom_oauth"
echo ""
echo "# Create the files by copying content"
echo "# Use Cloud Shell editor or vi/nano to create:"
echo "# - client_secrets.json"
echo "# - multi_channel_oauth_flow.py"
echo ""
echo "# Or upload using Cloud Shell upload button"
echo ""
echo "📋 OPTION 3: Direct copy commands"
echo "================================"
echo "If you're on the server, copy to home directory:"
echo ""
echo "cp /home/golde/tenxsom-ai-vertex/youtube-upload-pipeline/auth/client_secrets.json ~/"
echo "cp /home/golde/tenxsom-ai-vertex/multi_channel_oauth_flow.py ~/"
echo ""
echo "Then transfer to your local machine as needed."