# Google Cloud Build configuration for MCP Server
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:$COMMIT_SHA',
      '-t', 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:latest',
      '.'
    ]
    dir: 'useapi-mcp-server'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'tenxsom-mcp-server',
      '--image', 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '80',
      '--timeout', '900',
      '--set-env-vars', 'PYTHONPATH=/app/src,PYTHONUNBUFFERED=1',
      '--set-secrets', 'USEAPI_BEARER_TOKEN=useapi-bearer-token:latest,DATABASE_URL=mcp-database-url:latest',
      '--set-cloudsql-instances', '$_PROJECT_ID:us-central1:tenxsom-mcp-db'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:$COMMIT_SHA'
  - 'gcr.io/$_PROJECT_ID/tenxsom-mcp-server:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'