# Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tenxsom-mcp-server
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/sessionAffinity: "false"
        run.googleapis.com/cloudsql-instances: tenxsom-ai-1631088:us-central1:tenxsom-mcp-db
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      serviceAccountName: tenxsom-ai-1631088-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/tenxsom-ai-1631088/tenxsom-mcp-server:latest
        name: tenxsom-mcp-server
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: mcp-database-url
        - name: USEAPI_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: useapi-bearer-token
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true